# Generated by Django 5.2.17 on 2026-08-06 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_number', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=150, verbose_name='Asunto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('request_type', models.CharField(choices=[('INCIDENT', 'Incidente'), ('INQUIRY', 'Consulta'), ('COMPLAINT', 'Reclamo'), ('SUGGESTION', 'Sugerencia')], max_length=20, verbose_name='Tipo de solicitud')),
                ('incident_date', models.DateTimeField(verbose_name='Fecha del incidente')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/', verbose_name='Evidencia')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('ASSIGNED', 'Asignado'), ('IN_PROGRESS', 'En proceso'), ('ON_HOLD', 'En espera'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Agente asignado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_created', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('ASSIGNED', 'Asignado'), ('IN_PROGRESS', 'En proceso'), ('ON_HOLD', 'En espera'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], max_length=20, verbose_name='Estado')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de seguimiento')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_updates', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='service_desk.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-updated_at'],
            },
        ),
    ]
